/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UploadedEventDTO } from './uploadedEventDTO';
import { OriginDeviceDTO } from './originDeviceDTO';


export interface UploadedSignalDTO { 
    description?: string;
    value?: number;
    sourceDevice?: OriginDeviceDTO;
    events?: Array<UploadedEventDTO>;
}

