INSERT INTO country (name) VALUES ('India');
INSERT INTO country (name) VALUES ('Brazil');
INSERT INTO country (name) VALUES ('USA');
INSERT INTO country (name) VALUES ('Italy');
INSERT INTO country (name) VALUES ('Belarus');
INSERT INTO country (name) VALUES ('Belgium');
INSERT INTO country (name) VALUES ('Germany');
INSERT INTO country (name) VALUES ('Bulgaria');
INSERT INTO country (name) VALUES ('China');
INSERT INTO country (name) VALUES ('Canada');
INSERT INTO country (name) VALUES ('Columbia');
INSERT INTO country (name) VALUES ('Republic of the Congo');
INSERT INTO country (name) VALUES ('Denmark');
INSERT INTO country (name) VALUES ('Fiji');
INSERT INTO country (name) VALUES ('Georgia');
INSERT INTO country (name) VALUES ('Serbia');