INSERT INTO country (name) VALUES ('India');
INSERT INTO country (name) VALUES ('Brazil');
INSERT INTO country (name) VALUES ('USA');
INSERT INTO country (name) VALUES ('Italy');
INSERT INTO country (name) VALUES ('Belarus');
INSERT INTO country (name) VALUES ('Belgium');
INSERT INTO country (name) VALUES ('Germany');
INSERT INTO country (name) VALUES ('Bulgaria');
INSERT INTO country (name) VALUES ('China');
INSERT INTO country (name) VALUES ('Canada');
INSERT INTO country (name) VALUES ('Columbia');
INSERT INTO country (name) VALUES ('Republic of the Congo');
INSERT INTO country (name) VALUES ('Denmark');
INSERT INTO country (name) VALUES ('Fiji');
INSERT INTO country (name) VALUES ('Georgia');
INSERT INTO country (name) VALUES ('Serbia');
INSERT INTO country (name) VALUES ('Cuba');
INSERT INTO country (name) VALUES ('Cyprus');
INSERT INTO country (name) VALUES ('Croatia');
INSERT INTO country (name) VALUES ('Romania');
INSERT INTO country (name) VALUES ('Sweden');
INSERT INTO country (name) VALUES ('Norway');
INSERT INTO country (name) VALUES ('Hungary');
INSERT INTO country (name) VALUES ('Ireland');
INSERT INTO country (name) VALUES ('Japan');
INSERT INTO country (name) VALUES ('Venezuela');
INSERT INTO country (name) VALUES ('Luxembourg');
INSERT INTO country (name) VALUES ('Samoa');
INSERT INTO country (name) VALUES ('San Marino');
INSERT INTO country (name) VALUES ('Sao Tome and Principe');
INSERT INTO country (name) VALUES ('Saudi Arabia');
INSERT INTO country (name) VALUES ('Schaumburg-Lippe');
INSERT INTO country (name) VALUES ('Senegal');
INSERT INTO country (name) VALUES ('Seychelles');
INSERT INTO country (name) VALUES ('Sierra Leone');
INSERT INTO country (name) VALUES ('Singapore');
INSERT INTO country (name) VALUES ('Slovakia');
INSERT INTO country (name) VALUES ('Slovenia');
INSERT INTO country (name) VALUES ('South Africa');
INSERT INTO country (name) VALUES ('South Sudan');
INSERT INTO country (name) VALUES ('Spain');
